version: "3.7"
services:
  nodejs-app:
    build: "./app"
    container_name: ehya_v2
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongodb_v1/main_database_1?authSource=admin&retryWrites=true
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - REDIS_IP=127.0.0.1
      - SUPER_ADMIN_USER=root
      - SUPER_ADMIN_PASSWORD=password
      - PORT=8000
      - HAS_CLUSTER=false
      - SESSION_SECRET_KEY=fjdu434687gshfd
      - SESSION_LIFETIME_DAYS=7
      - DOCS_URL=http://87.107.105.66/docs


  mongo:
    image: mongo
    container_name: mongodb_v1
    restart: always
    ports:
      - 27025:27017
    volumes:
      - type: bind
        source: './volumes/db'
        target: '/data/db'

    environment:
      MONGO_INITDB_DATABASE: main_database_1


  redis:
    image: redis
    container_name: redis_v2
    restart: always
    ports:
      - '6379:6379'
    logging:
      driver: none
