version: "3.7"
services:
  nodejs-app:
    build: "./app"
    container_name: ehya_v2
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/main_database
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - REDIS_IP=127.0.0.1


  mongo:
    image: mongo:5.0-rc-focal
    container_name: mongodb_v2
    restart: always
    ports:
      - 27025:27017
    volumes:
      - type: bind
        source: './volumes/db'
        target: '/data/db'
#      - ./mongod.conf:/etc/mongod.conf
#    command: [ "mongod", "--config", "/etc/mongod.conf" ]

    environment:
      MONGO_INITDB_DATABASE: main_database

  redis:
    image: redis
    container_name: redis_v2
    restart: always
    ports:
      - '6379:6379'
    logging:
      driver: none
